apiVersion: v1
kind: Service
metadata:
  name: doca-telemetry-metrics
  namespace: network-operator
  labels:
    app.kubernetes.io/name: doca-telemetry-metrics
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: doca-telemetry
  ports:
    - name: metrics
      port: 9189
      targetPort: 9189
      protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: doca-telemetry-rdma
  namespace: llm-d-monitoring
spec:
  namespaceSelector:
    matchNames:
      - network-operator
  selector:
    matchLabels:
      app.kubernetes.io/name: doca-telemetry-metrics
  endpoints:
    - port: metrics
      interval: 10s
